apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vault
  labels:
    app.kubernetes.io/name: test-vault
    app.kubernetes.io/instance: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-vault
      app.kubernetes.io/instance: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-vault
        app.kubernetes.io/instance: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.13.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8200
              name: http