apiVersion: v1
kind: Service
metadata:
  name: test-vault
  labels:
    app.kubernetes.io/name: test-vault
    app.kubernetes.io/instance: vault
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app.kubernetes.io/name: test-vault
    app.kubernetes.io/instance: vault