apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend
  labels:
    app.kubernetes.io/name: test-frontend
    app.kubernetes.io/instance: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: test-frontend
      app.kubernetes.io/instance: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-frontend
        app.kubernetes.io/instance: frontend
    spec:
      containers:
        - name: test-frontend
          image: ifilyaninitmo/itdt-contained-frontend:master
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: test-frontend
                  key: REACT_APP_USERNAME
            - name: REACT_APP_COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: test-frontend
                  key: REACT_APP_COMPANY_NAME
          ports:
            - containerPort: 3000
              name: http