apiVersion: v1
kind: Secret
metadata:
  name: test-frontend-secret
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN ENCRYPTED PRIVATE KEY-----
    -----END ENCRYPTED PRIVATE KEY-----